### ISSUE TITLE
KarlSaberV1.0.0.zip 1.3.0p1 update

### ISSUE THREAD

**Issue by Bofh5** [RedBrumbler/BeatOnCustomSabers#53]
Update: Replacing the beatonmod.json in the V1 zip with the one from V2 fixed it :)

Hi RedBrumbler
This one isn't working unfortunately :( V2 is fine but this was my favourite

Installed using sidequest 0.6.7 

INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl1354101940.tmp/base.apk: Androidmanifest.xml

**Comment by RedBrumbler** [comment]
just fixed it, closing issue
